# Generated by Django 4.2.5 on 2023-10-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_alter_order_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='price',
        ),
    ]
