# Generated by Django 4.2.5 on 2023-10-04 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_rename_total_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
    ]
